version: 2

build:
  image: latest

formats:
  - epub
  - pdf

sphinx:
  builder: htmldir
  configuration: docs/conf.py
  fail_on_warning: false

python:
  version: 3.6
  requirements: requirements.txt
  system_packages: true

submodules:
  include: all
  recursive: true
