version: 2

build:
  image: latest

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
  version: 3.6
  system_packages: true
  install:
    - requirements: requirements.txt

submodules:
  include: all
  recursive: true
