version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  version: 3
  install:
    - requirements: requirements.txt
    - method: pip
        path: .
        extra_requirements:
          - docs
